### ISSUE TITLE
Sample app not working - Bug

### ISSUE THREAD

**Issue by f-odhiambo** [DBCG/CqlEvaluatorSampleApp#1]
Seems like there are some libraries that are not syncing anymore and closing the app to terminate before launch 

1. Could not find org.opencds.cqf.cql:evaluator:1.2.0-SNAPSHOT.
2. Could not find org.opencds.cqf.cql:evaluator.builder:1.2.0-SNAPSHOT.
3. Could not find org.opencds.cqf.cql:evaluator.dagger:1.2.0-SNAPSHOT.

![image](https://user-images.githubusercontent.com/4540684/120495243-316af980-c3c5-11eb-9fd3-1d0ab17a5259.png)

**Comment by MuhammadSalman-7214** [comment]
Yeah I am also facing the same error

**Comment by f-odhiambo** [comment]
cc @JPercival let me know if there has been any recent changes that may have contributed to the above issue

**Comment by JPercival** [comment]
Hi all!

SNAPSHOTS are prereleases in the Maven ecosystem and they can expire. Turns out 1.2.0-SNAPSHOT did. I updated the `master` branch to use the 1.2.0 release. Please give it a go.

**Comment by f-odhiambo** [comment]
Thanks for the update. Now working fine. We plan to review this and give some feedback that can be used for its enhancement. I will  revert back soon
